Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f8ca728008ff5af4
      Tags:
        - Key: "Name"
          Value: "Changeset12"